import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  const SideNavBar = () => {
    return (
      <div className="fixed  z-10  hidden h-full bg-white md:flex md:w-[5%]">
        <div className="absolute bottom-2 text-black ">
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
      </div>
    );
  };

  const BottomNavBar = () => {
    return (
      <div className="absolute bottom-0 flex h-[7%] w-full items-center justify-center bg-slate-100 md:hidden">
        <div className="text-black ">
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
      </div>
    );
  };

  const CreatePostWizard = () => {
    const { user } = useUser();
    console.log("user", user);
    if (!user) return null;

    return (
      <div className="justify-star gap- flex h-1/6 items-center gap-5 border-b pl-5 md:w-[95%]">
        <Image
          src={user.profileImageUrl}
          width={50}
          height={50}
          className="rounded-full"
          alt={`${user.username!}'s profile picture`}
        ></Image>
        <input
          type="text"
          placeholder="Type some text..."
          className="grow bg-transparent outline-none"
        />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="relative flex h-screen w-full">
          <SideNavBar />
          <div className="relative flex w-full grow flex-col md:items-end">
            {user.isSignedIn && <CreatePostWizard></CreatePostWizard>}
            <div className="w-full border-opacity-40">
              {isLoading && <div>Loading...</div>}
              {!data && <div>Something went wrong</div>}
              {[...data, ...data]?.map((post) => (
                <div
                  key={post.id}
                  className="flex flex-col items-center justify-center border-b border-white py-4 "
                >
                  {post.content}
                  <Image
                    src={post.catImageURL}
                    alt={`${post.authorId}'s cat image`}
                    width={120}
                    height={120}
                  ></Image>
                </div>
              ))}
            </div>
            <BottomNavBar />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
